#pragma once

// GLFW Keycode
#define MAXY_KEY_SPACE                  32
#define MAXY_KEY_APOSTROPHE             39
#define MAXY_KEY_COMMA                  44
#define MAXY_KEY_MINUS                  45
#define MAXY_KEY_PERIOD                 46
#define MAXY_KEY_SLASH                  47
#define MAXY_KEY_0                      48
#define MAXY_KEY_1                      49
#define MAXY_KEY_2                      50
#define MAXY_KEY_3                      51
#define MAXY_KEY_4                      52
#define MAXY_KEY_5                      53
#define MAXY_KEY_6                      54
#define MAXY_KEY_7                      55
#define MAXY_KEY_8                      56
#define MAXY_KEY_9                      57
#define MAXY_KEY_SEMICOLON              59
#define MAXY_KEY_EQUAL                  61
#define MAXY_KEY_A                      65
#define MAXY_KEY_B                      66
#define MAXY_KEY_C                      67
#define MAXY_KEY_D                      68
#define MAXY_KEY_E                      69
#define MAXY_KEY_F                      70
#define MAXY_KEY_G                      71
#define MAXY_KEY_H                      72
#define MAXY_KEY_I                      73
#define MAXY_KEY_J                      74
#define MAXY_KEY_K                      75
#define MAXY_KEY_L                      76
#define MAXY_KEY_M                      77
#define MAXY_KEY_N                      78
#define MAXY_KEY_O                      79
#define MAXY_KEY_P                      80
#define MAXY_KEY_Q                      81
#define MAXY_KEY_R                      82
#define MAXY_KEY_S                      83
#define MAXY_KEY_T                      84
#define MAXY_KEY_U                      85
#define MAXY_KEY_V                      86
#define MAXY_KEY_W                      87
#define MAXY_KEY_X                      88
#define MAXY_KEY_Y                      89
#define MAXY_KEY_Z                      90
#define MAXY_KEY_LEFT_BRACKET           91
#define MAXY_KEY_BACKSLASH              92
#define MAXY_KEY_RIGHT_BRACKET          93
#define MAXY_KEY_GRAVE_ACCENT           96
#define MAXY_KEY_WORLD_1                161
#define MAXY_KEY_WORLD_2                162

#define MAXY_KEY_ESCAPE                 256
#define MAXY_KEY_ENTER                  257
#define MAXY_KEY_TAB                    258
#define MAXY_KEY_BACKSPACE              259
#define MAXY_KEY_INSERT                 260
#define MAXY_KEY_DELETE                 261
#define MAXY_KEY_RIGHT                  262
#define MAXY_KEY_LEFT                   263
#define MAXY_KEY_DOWN                   264
#define MAXY_KEY_UP                     265
#define MAXY_KEY_PAGE_UP                266
#define MAXY_KEY_PAGE_DOWN              267
#define MAXY_KEY_HOME                   268
#define MAXY_KEY_END                    269
#define MAXY_KEY_CAPS_LOCK              280
#define MAXY_KEY_SCROLL_LOCK            281
#define MAXY_KEY_NUM_LOCK               282
#define MAXY_KEY_PRINT_SCREEN           283
#define MAXY_KEY_PAUSE                  284
#define MAXY_KEY_F1                     290
#define MAXY_KEY_F2                     291
#define MAXY_KEY_F3                     292
#define MAXY_KEY_F4                     293
#define MAXY_KEY_F5                     294
#define MAXY_KEY_F6                     295
#define MAXY_KEY_F7                     296
#define MAXY_KEY_F8                     297
#define MAXY_KEY_F9                     298
#define MAXY_KEY_F10                    299
#define MAXY_KEY_F11                    300
#define MAXY_KEY_F12                    301
#define MAXY_KEY_F13                    302
#define MAXY_KEY_F14                    303
#define MAXY_KEY_F15                    304
#define MAXY_KEY_F16                    305
#define MAXY_KEY_F17                    306
#define MAXY_KEY_F18                    307
#define MAXY_KEY_F19                    308
#define MAXY_KEY_F20                    309
#define MAXY_KEY_F21                    310
#define MAXY_KEY_F22                    311
#define MAXY_KEY_F23                    312
#define MAXY_KEY_F24                    313
#define MAXY_KEY_F25                    314
#define MAXY_KEY_KP_0                   320
#define MAXY_KEY_KP_1                   321
#define MAXY_KEY_KP_2                   322
#define MAXY_KEY_KP_3                   323
#define MAXY_KEY_KP_4                   324
#define MAXY_KEY_KP_5                   325
#define MAXY_KEY_KP_6                   326
#define MAXY_KEY_KP_7                   327
#define MAXY_KEY_KP_8                   328
#define MAXY_KEY_KP_9                   329
#define MAXY_KEY_KP_DECIMAL             330
#define MAXY_KEY_KP_DIVIDE              331
#define MAXY_KEY_KP_MULTIPLY            332
#define MAXY_KEY_KP_SUBTRACT            333
#define MAXY_KEY_KP_ADD                 334
#define MAXY_KEY_KP_ENTER               335
#define MAXY_KEY_KP_EQUAL               336
#define MAXY_KEY_LEFT_SHIFT             340
#define MAXY_KEY_LEFT_CONTROL           341
#define MAXY_KEY_LEFT_ALT               342
#define MAXY_KEY_LEFT_SUPER             343
#define MAXY_KEY_RIGHT_SHIFT            344
#define MAXY_KEY_RIGHT_CONTROL          345
#define MAXY_KEY_RIGHT_ALT              346
#define MAXY_KEY_RIGHT_SUPER            347
#define MAXY_KEY_MENU                   348